web:
  build: .
  command: develop
  volumes:
    - .:/rw_adapter_arcgis
  ports:
    - '3035:3035'
  links:
    - postgres
    - redis
  env_file: dev.env

postgres:
  image: postgres
  container_name: postgres_rw_adapter_arcgis

redis:
  image: redis
  container_name: redis_rw_adapter_arcgis
